# Generated by Django 3.0.6 on 2020-05-08 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.FileField(blank=True, upload_to='uploads/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('is_premium', models.BooleanField(default=False)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('psn_gamertag', models.CharField(blank=True, max_length=100)),
                ('xbox_gamertag', models.CharField(blank=True, max_length=100)),
                ('steam_gamertag', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
