# Generated by Django 3.0.6 on 2020-05-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresetcodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcodes',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
